### ISSUE TITLE
Qordoba breaks CMS page save if no preference is created

### ISSUE THREAD

**Issue by kassner** [Qordobacode/magento-2#12]
Hi,

I am not able to install the Qordoba module because there is no treatment when there is no preference set. More technically, the method `Qordoba\Connector\Model\ResourceModel\Preferences::getDefault()` can return `false` instead of a string, and then it breaks later:

Stack trace from `bin/magento setup:upgrade`:

```
#0 /var/www/html/vendor/qordoba/magento2-connector/Model/ContentRepository.php(272): Qordoba\Connector\Model\PreferencesRepository->getById(false)
#1 /var/www/html/vendor/qordoba/magento2-connector/Model/ContentRepository.php(612): Qordoba\Connector\Model\ContentRepository->getDefaultPreference()
#2 /var/www/html/vendor/qordoba/magento2-connector/Observer/AfterSaveContent.php(40): Qordoba\Connector\Model\ContentRepository->repairByContent(Object(Magento\Cms\Model\Page))
#3 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Qordoba\Connector\Observer\AfterSaveContent->execute(Object(Magento\Framework\Event\Observer))
#4 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Qordoba\Connector\Observer\AfterSaveContent), Object(Magento\Framework\Event\Observer))
#5 /var/www/html/vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#6 /var/www/html/generated/code/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch('cms_page_save_a...', Array)
#7 /var/www/html/vendor/magento/framework/Model/AbstractModel.php(818): Magento\Staging\Model\Event\Manager\Proxy->dispatch('cms_page_save_a...', Array)
#8 /var/www/html/vendor/magento/framework/EntityManager/Observer/AfterEntitySave.php(34): Magento\Framework\Model\AbstractModel->afterSave()
#9 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Magento\Framework\EntityManager\Observer\AfterEntitySave->execute(Object(Magento\Framework\Event\Observer))
#10 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Framework\EntityManager\Observer\AfterEntitySave), Object(Magento\Framework\Event\Observer))
#11 /var/www/html/vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#12 /var/www/html/generated/code/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch('magento_cms_api...', Array)
#13 /var/www/html/vendor/magento/framework/EntityManager/EventManager.php(52): Magento\Staging\Model\Event\Manager\Proxy->dispatch('magento_cms_api...', Array)
#14 /var/www/html/vendor/magento/module-staging/Model/Operation/Update.php(210): Magento\Framework\EntityManager\EventManager->dispatchEntityEvent('Magento\\Cms\\Api...', 'save_after', Array)
#15 /var/www/html/vendor/magento/framework/EntityManager/EntityManager.php(96): Magento\Staging\Model\Operation\Update->execute(Object(Magento\Cms\Model\Page), Array)
#16 /var/www/html/vendor/magento/module-cms/Model/ResourceModel/Page.php(397): Magento\Framework\EntityManager\EntityManager->save(Object(Magento\Cms\Model\Page))
#17 /var/www/html/generated/code/Magento/Cms/Model/ResourceModel/Page/Interceptor.php(141): Magento\Cms\Model\ResourceModel\Page->save(Object(Magento\Cms\Model\Page))
#18 /var/www/html/vendor/magento/framework/Model/AbstractModel.php(647): Magento\Cms\Model\ResourceModel\Page\Interceptor->save(Object(Magento\Cms\Model\Page))
#19 [redacted]
#20 [redacted]
#21 [redacted]
#22 /var/www/html/setup/src/Magento/Setup/Model/Installer.php(791): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data')
#23 /var/www/html/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php(94): Magento\Setup\Model\Installer->installDataFixtures()
#24 /var/www/html/vendor/symfony/console/Command/Command.php(241): Magento\Setup\Console\Command\UpgradeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/vendor/symfony/console/Application.php(843): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\UpgradeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/vendor/magento/framework/Console/Cli.php(104): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/vendor/symfony/console/Application.php(117): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#30 {main}
```

In the redacted steps, there is a custom setup script (implementing `Magento\Framework\Setup\UpgradeDataInterface`) that creates CMS pages. Since the Qordoba tables were created, but no rows were added to the `qordoba_preference` table (because I was not able to access the admin panel yet), the module fails.

## Sugestions

Ideal scenario: the module will handle when no preferences are created and not attempt to do anything, just bypass (i.e.: do a check in the observers before they attempt to use Qordoba).

Less ideal but also works: the Qordoba module has a setup script that created one default row in the `qordoba_preference`table if none yet exists. By doing so, `bin/magento setup:upgrade` works as expected, but I am not sure what are the implications later when I'll try to configure the module.

Thanks!

**Comment by kassner** [comment]
Current workaround I'm using to get the extension installed. Not ideal, but gets `setup:upgrade` through it.

```
--- Setup/InstallSchema.php	2018-07-05 09:49:59.190000000 +0000
+++ Setup/InstallSchema.php	2018-07-05 09:50:07.660000000 +0000
@@ -56,9 +56,22 @@
         $this->createTranslatedContentTable($installer);
         $this->createMappingTable($installer);
 
+        $this->createDefaultPreference($setup);
+
         $installer->endSetup();
     }
 
+    private function createDefaultPreference(SchemaSetupInterface $setup)
+    {
+        $setup->getConnection()->insert(self::QORDOBA_PREFERENCE_TABLE, [
+            'organization_id' => 1,
+            'store_id' => 1,
+            'project_id' => 1,
+            'state' => 1,
+            'is_default' => 1,
+        ]);
+    }
+
     /**
      * @param SchemaSetupInterface $setup
      * @throws \Zend_Db_Exception
```

**Comment by RadikChernyshov** [comment]
@kassner thank you for your help and suggestion.
The issue is fixed. Please update your M2 installation.

**Comment by elvinristi** [comment]
Hello @RadikChernyshov ,

Shouldn't https://github.com/Qordobacode/magento-2/blob/master/Observer/AfterSaveContent.php#L36 be fixed and checked if solution is enabled and if configuration is existing and only then to continue with execution due following observers:

- https://github.com/Qordobacode/magento-2/blob/master/etc/events.xml#L27

Our case is that we have empty database and setup script is creating cms-pages/blocks and now this event kicks in. I think this 1.0.14 doesn't fix this issue based looked code.
